/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginForm;

import AdminpPortal.admin_adddoctor;
import DBConnectionP.DBConnection;
import DoctorPortal.doctor_mainmenu;
import ReceptionistPortal.receptionist_mainmenu;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author AbdulRehman
 */
public class loginsection extends javax.swing.JFrame {
    
    DBConnection conn = new DBConnection();
    
    public loginsection() {
        initComponents();
        _pass_error.setVisible(false);
        _username_error.setVisible(false);
        _usertype_error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        registrationdate = new javax.swing.JTextField();
        Loginbtn = new javax.swing.JButton();
        _usertype_error = new javax.swing.JLabel();
        username_ed = new javax.swing.JTextField();
        password_ed = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        logintype_combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        _username_error = new javax.swing.JLabel();
        _pass_error = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timegetting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(947, 708));
        setResizable(false);
        setSize(new java.awt.Dimension(947, 708));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/admin (1).png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 10, 130, 130);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        registrationdate.setEditable(false);
        registrationdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registrationdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registrationdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        registrationdate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(registrationdate);
        registrationdate.setBounds(330, 10, 160, 30);

        Loginbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Loginbtn.setText("Login");
        Loginbtn.setBorder(new javax.swing.border.MatteBorder(null));
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });
        jPanel3.add(Loginbtn);
        Loginbtn.setBounds(420, 380, 120, 40);

        _usertype_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _usertype_error.setForeground(new java.awt.Color(255, 0, 0));
        _usertype_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _usertype_error.setText("*");
        jPanel3.add(_usertype_error);
        _usertype_error.setBounds(480, 300, 20, 20);

        username_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        username_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(username_ed);
        username_ed.setBounds(310, 140, 230, 40);

        password_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        password_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(password_ed);
        password_ed.setBounds(310, 230, 230, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(310, 200, 150, 30);

        logintype_combo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        logintype_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User", "Admin", "Doctor", "Receptionist" }));
        logintype_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logintype_comboActionPerformed(evt);
            }
        });
        jPanel3.add(logintype_combo);
        logintype_combo.setBounds(310, 290, 170, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Username");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(310, 110, 150, 30);

        _username_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _username_error.setForeground(new java.awt.Color(255, 0, 0));
        _username_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _username_error.setText("*");
        jPanel3.add(_username_error);
        _username_error.setBounds(540, 150, 20, 20);

        _pass_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _pass_error.setForeground(new java.awt.Color(255, 0, 0));
        _pass_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _pass_error.setText("*");
        jPanel3.add(_pass_error);
        _pass_error.setBounds(540, 240, 20, 20);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(60, 170, 810, 490);

        jLabel6.setBackground(new java.awt.Color(0, 102, 153));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                Login Portal");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel4.add(jLabel6);
        jLabel6.setBounds(230, 50, 710, 70);

        timegetting.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        timegetting.setText("Time");
        jPanel4.add(timegetting);
        timegetting.setBounds(430, 10, 120, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 940, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logintype_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logintype_comboActionPerformed
        if(logintype_combo.getSelectedItem().equals("Select User")){_usertype_error.setVisible(true);}
        if(logintype_combo.getSelectedItem().equals("Admin")){_usertype_error.setVisible(false);}
        if(logintype_combo.getSelectedItem().equals("Doctor")){_usertype_error.setVisible(false);}
        if(logintype_combo.getSelectedItem().equals("Receptionist")){_usertype_error.setVisible(false);}
        
    }//GEN-LAST:event_logintype_comboActionPerformed

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        boolean chkfiled = false;
        
        if(username_ed.getText().equals("")){_username_error.setVisible(true);chkfiled = false;}
        if(password_ed.getText().equals("")){_pass_error.setVisible(true);chkfiled = false;}
        if(logintype_combo.getSelectedItem().equals("Select User")){_usertype_error.setVisible(true);chkfiled = false;}
        
        if(!username_ed.getText().isEmpty()
            && !password_ed.getText().isEmpty()
            && !logintype_combo.getSelectedItem().equals("Select User")){chkfiled = true;}
        
        if(chkfiled==false){JOptionPane.showMessageDialog(null, "Please Fill the Fileds");}
        
        if(chkfiled==true){
            _username_error.setVisible(false);
            _pass_error.setVisible(false);
            _usertype_error.setVisible(false);
            
            try{
                conn.OpenConnection();
                if(logintype_combo.getSelectedItem().equals("Admin")){
                    boolean loginok = false;
                    String adminquery="select username,pass from adminprotal";
                    conn.GetData(adminquery);
                    while(conn.rst.next()){
                      String username =  conn.rst.getString("username");
                      String password = conn.rst.getString("pass");
                      
                        if(username_ed.getText().equals(username) && password_ed.getText().equals(password)){
                            loginok=true;
                            JOptionPane.showMessageDialog(null, "Successfully Login ...!");
                            AdminpPortal.admin_adddoctor  aad = new admin_adddoctor();
                            aad.setVisible(true);
                            dispose();
                        }
                    }
                   if(loginok==false){JOptionPane.showMessageDialog(null, "Login Failed ...!\n Incorrect Username or Password");}
                }
                
                if(logintype_combo.getSelectedItem().equals("Doctor")){
                    boolean loginok = false;
                    String adminquery="select username,pass from Doctor";
                    conn.GetData(adminquery);
                    while(conn.rst.next()){
                      String username =  conn.rst.getString("username");
                      String password = conn.rst.getString("pass");
                      
                        if(username_ed.getText().equals(username) && password_ed.getText().equals(password)){
                            loginok=true;
                            JOptionPane.showMessageDialog(null, "Successfully Login ...!");
                            DoctorPortal.doctor_mainmenu ddm = new doctor_mainmenu();
                            ddm.setVisible(true);
                            dispose();
                        }
                    }
                   if(loginok==false){JOptionPane.showMessageDialog(null, "Login Failed ...!\n Incorrect Username or Password");}
                }
                
                if(logintype_combo.getSelectedItem().equals("Receptionist")){
                    boolean loginok = false;
                    String adminquery="select username,pass from Recept";
                    conn.GetData(adminquery);
                    while(conn.rst.next()){
                      String username =  conn.rst.getString("username");
                      String password = conn.rst.getString("pass");
                      
                        if(username_ed.getText().equals(username) && password_ed.getText().equals(password)){
                            loginok=true;
                            JOptionPane.showMessageDialog(null, "Successfully Login ...!");
                            ReceptionistPortal.receptionist_mainmenu rmm = new receptionist_mainmenu();
                            rmm.setVisible(true);
                            dispose();
                        }
                    }
                   if(loginok==false){JOptionPane.showMessageDialog(null, "Login Failed ...!\n Incorrect Username or Password");}
                }
                
            }catch(SQLException e) {System.out.println(e);}
        }
    }//GEN-LAST:event_LoginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginsection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbtn;
    private javax.swing.JLabel _pass_error;
    private javax.swing.JLabel _username_error;
    private javax.swing.JLabel _usertype_error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> logintype_combo;
    private javax.swing.JPasswordField password_ed;
    private javax.swing.JTextField registrationdate;
    private javax.swing.JLabel timegetting;
    private javax.swing.JTextField username_ed;
    // End of variables declaration//GEN-END:variables
}
