/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginForm;

/**
 *
 * @author AbdulRehman
 */
public class MainLoginForm extends javax.swing.JFrame {

    /**
     * Creates new form MainLoginForm
     */
    public MainLoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adminform_btn = new javax.swing.JButton();
        doctorform_btn = new javax.swing.JButton();
        receptionisform_tbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(870, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                      Hospital Management System");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 20, 870, 50);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("     Login As");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 100, 140, 40);

        adminform_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminform_btn.setForeground(new java.awt.Color(0, 51, 102));
        adminform_btn.setText("Admin");
        adminform_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminform_btnActionPerformed(evt);
            }
        });
        getContentPane().add(adminform_btn);
        adminform_btn.setBounds(220, 330, 140, 50);

        doctorform_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doctorform_btn.setForeground(new java.awt.Color(0, 51, 102));
        doctorform_btn.setText("Doctor");
        doctorform_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorform_btnActionPerformed(evt);
            }
        });
        getContentPane().add(doctorform_btn);
        doctorform_btn.setBounds(380, 330, 140, 50);

        receptionisform_tbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        receptionisform_tbtn.setForeground(new java.awt.Color(0, 51, 102));
        receptionisform_tbtn.setText("Receptionist");
        receptionisform_tbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionisform_tbtnActionPerformed(evt);
            }
        });
        getContentPane().add(receptionisform_tbtn);
        receptionisform_tbtn.setBounds(540, 330, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/r9.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 870, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void receptionisform_tbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionisform_tbtnActionPerformed
        // TODO add your handling code here:
        ReceptionistForm receptionistform = new ReceptionistForm();
        receptionistform.setVisible(true);
        dispose();
    }//GEN-LAST:event_receptionisform_tbtnActionPerformed

    private void adminform_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminform_btnActionPerformed
        // TODO add your handling code here:
        AdminForm adminform = new AdminForm();
        adminform.setVisible(true);
        dispose();
    }//GEN-LAST:event_adminform_btnActionPerformed

    private void doctorform_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorform_btnActionPerformed
        // TODO add your handling code here:
        DoctorForm doctorform = new DoctorForm();
        doctorform.setVisible(true);
        dispose();
    }//GEN-LAST:event_doctorform_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainLoginForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminform_btn;
    private javax.swing.JButton doctorform_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton receptionisform_tbtn;
    // End of variables declaration//GEN-END:variables
}
