/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DoctorPortal;

import DBConnectionP.DBConnection;
import LoginForm.loginsection;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author AbdulRehman
 */
public class doctor_mainmenu extends javax.swing.JFrame {

    DBConnection conn = new DBConnection();
    
    void showtime(){
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("hh:mm:ss a");
            timegetting.setText(t.format(d));
        }).start();   
    }
    
    void showdate(){
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("yyyy-MM-dd");
            registrationdate.setText(t.format(d));
        }).start();
    }
    
    public doctor_mainmenu() {
        initComponents();
        _appid_error.setVisible(false);
    }

    public doctor_mainmenu(int id , String username){
        initComponents();
        _appid_error.setVisible(false);
        dd_id_tv.setText(String.valueOf(id));
        dd_username_tv.setText(username);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ap_patlname_ed = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        registrationdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        ap_patid_ed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        appointmentid_ed = new javax.swing.JTextField();
        getingid = new javax.swing.JButton();
        ap_patage_ed = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ap_patgender_ed = new javax.swing.JTextField();
        ap_patfname_ed = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dd_username_tv = new javax.swing.JLabel();
        dd_id_tv = new javax.swing.JTextField();
        _appid_error = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        apptable = new javax.swing.JTable();
        logout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        timegetting = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(947, 708));
        setResizable(false);
        setSize(new java.awt.Dimension(947, 708));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/doctor.png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 20, 130, 140);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Last Name");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 240, 90, 30);

        ap_patlname_ed.setEditable(false);
        ap_patlname_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ap_patlname_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ap_patlname_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(ap_patlname_ed);
        ap_patlname_ed.setBounds(130, 240, 150, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("First Name");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 190, 90, 30);

        registrationdate.setEditable(false);
        registrationdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registrationdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registrationdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(registrationdate);
        registrationdate.setBounds(380, 20, 150, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Patient ID : ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 140, 70, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Checked");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(jButton4);
        jButton4.setBounds(290, 420, 150, 40);

        ap_patid_ed.setEditable(false);
        ap_patid_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ap_patid_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ap_patid_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(ap_patid_ed);
        ap_patid_ed.setBounds(130, 140, 59, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Appoint ID : ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 100, 80, 30);

        appointmentid_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        appointmentid_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        appointmentid_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        appointmentid_ed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                appointmentid_edKeyTyped(evt);
            }
        });
        jPanel3.add(appointmentid_ed);
        appointmentid_ed.setBounds(130, 100, 59, 30);

        getingid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getingid.setText("Get");
        getingid.setBorder(new javax.swing.border.MatteBorder(null));
        getingid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getingidActionPerformed(evt);
            }
        });
        jPanel3.add(getingid);
        getingid.setBounds(220, 100, 60, 30);

        ap_patage_ed.setEditable(false);
        ap_patage_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ap_patage_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ap_patage_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(ap_patage_ed);
        ap_patage_ed.setBounds(130, 290, 150, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Age");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(60, 290, 40, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Gender");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(50, 340, 50, 30);

        ap_patgender_ed.setEditable(false);
        ap_patgender_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ap_patgender_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ap_patgender_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(ap_patgender_ed);
        ap_patgender_ed.setBounds(130, 340, 150, 30);

        ap_patfname_ed.setEditable(false);
        ap_patfname_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ap_patfname_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ap_patfname_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(ap_patfname_ed);
        ap_patfname_ed.setBounds(130, 190, 150, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("D ID : ");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(720, 20, 40, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("D Name : ");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(700, 60, 60, 30);

        dd_username_tv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dd_username_tv.setText("Null");
        jPanel3.add(dd_username_tv);
        dd_username_tv.setBounds(770, 60, 120, 30);

        dd_id_tv.setEditable(false);
        dd_id_tv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dd_id_tv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dd_id_tv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(dd_id_tv);
        dd_id_tv.setBounds(770, 20, 60, 30);

        _appid_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _appid_error.setForeground(new java.awt.Color(255, 0, 0));
        _appid_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _appid_error.setText("*");
        jPanel3.add(_appid_error);
        _appid_error.setBounds(190, 110, 20, 10);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        apptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AppID", "DID", "PatID", "PFName", "PLName", "Status", "APDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(apptable);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(550, 120, 350, 330);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(10, 170, 920, 490);

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logout.setText("Logout");
        logout.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel4.add(logout);
        logout.setBounds(760, 70, 150, 30);

        jLabel6.setBackground(new java.awt.Color(0, 102, 153));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                      Doctor Portal");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel4.add(jLabel6);
        jLabel6.setBounds(230, 50, 710, 70);

        timegetting.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        timegetting.setText("Time");
        jPanel4.add(timegetting);
        timegetting.setBounds(430, 10, 120, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Appointments");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(390, 130, 190, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 940, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void appointmentid_edKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appointmentid_edKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)  || (c==KeyEvent.VK_DELETE) )){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_appointmentid_edKeyTyped

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        LoginForm.loginsection lfl = new loginsection();
        lfl.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void getingidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getingidActionPerformed
        if(appointmentid_ed.getText().equals("")){
            _appid_error.setVisible(true);
        }
        if(appointmentid_ed.getText().equals("")){_appid_error.setVisible(true);}
        else{
            boolean ispresnt1 = false;
            _appid_error.setVisible(false);
            try{
                conn.OpenConnection();
//                String query = "select rpid , fname,lname,age,gname from RegPatient p ,gender g where p.sexid=g.gid and rpid="+appointmentid_ed.getText();
                String query = "select apid ,p.rpid ,fname , lname ,age  , gname from appointment a , regpatient p , gender g where p.sexid=g.gid and  a.rpid=p.rpid and a.apid="+appointmentid_ed.getText();
                conn.GetData(query);
                while(conn.rst.next()){
                    ispresnt1 = true;
                    ap_patid_ed.setText(String.valueOf(conn.rst.getInt("rpid")));
                    ap_patfname_ed.setText(conn.rst.getString("fname"));
                    ap_patlname_ed.setText(conn.rst.getString("lname"));
                    ap_patgender_ed.setText(conn.rst.getString("gname"));
                    ap_patage_ed.setText(String.valueOf(conn.rst.getInt("age")));
                   break;
                }
                conn.CloseConnection();
                if(ispresnt1 == false){
                    ap_patid_ed.setText("");
                    ap_patfname_ed.setText("");
                    ap_patlname_ed.setText("");
                    ap_patgender_ed.setText("");
                    ap_patage_ed.setText("");
                    JOptionPane.showMessageDialog(null, "Sorry Not Found such Patient");
                    
                }
            }catch(SQLException e ){System.out.println(e);}
            
        }
        
    }//GEN-LAST:event_getingidActionPerformed

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctor_mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctor_mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctor_mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctor_mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new doctor_mainmenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _appid_error;
    private javax.swing.JTextField ap_patage_ed;
    private javax.swing.JTextField ap_patfname_ed;
    private javax.swing.JTextField ap_patgender_ed;
    private javax.swing.JTextField ap_patid_ed;
    private javax.swing.JTextField ap_patlname_ed;
    private javax.swing.JTextField appointmentid_ed;
    private javax.swing.JTable apptable;
    private javax.swing.JTextField dd_id_tv;
    private javax.swing.JLabel dd_username_tv;
    private javax.swing.JButton getingid;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logout;
    private javax.swing.JTextField registrationdate;
    private javax.swing.JLabel timegetting;
    // End of variables declaration//GEN-END:variables
}
