/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReceptionistPortal;

import DBConnectionP.DBConnection;
import LoginForm.loginsection;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author AbdulRehman
 */
public class receptionist_billforadmit extends javax.swing.JFrame {

    DBConnection conn = new DBConnection();
    
    int id = -1 , ramount=-1 , roomno=-1;
    String username = null;
    String dischargedatee = null;
    String todaydate = null;
    String chkinDate = null;
    String chkoutDate = null;
    
  
    public receptionist_billforadmit() {
        initComponents();
        showtime();
        showdate();
        
        _admitid_error.setVisible(false);
        _searching_error.setVisible(false);
        _discharge_error.setVisible(false);
        bl_id_tv.setText(conn.getID("select billid from patientbill ORDER BY billid DESC Fetch first 1 rows only"));
    }

    public receptionist_billforadmit(int id , String username) {
        initComponents();
        showtime();
        showdate();
        this.id=id;
        this.username=username;
        rr_patrecp_tv.setText(String.valueOf(id));
        receptionistname.setText(username);
        
        _admitid_error.setVisible(false);
        _searching_error.setVisible(false);
        _discharge_error.setVisible(false);
        
        bl_id_tv.setText(conn.getID("select billid from patientbill ORDER BY billid DESC Fetch first 1 rows only"));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        timegetting = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bl_discharge_ed = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        resetall = new javax.swing.JButton();
        checkedoutbtn = new javax.swing.JButton();
        bl_adid_ed = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        bl_days_ed = new javax.swing.JTextField();
        gettingadmitid = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        bl_amount_ed = new javax.swing.JTextField();
        gettingdischargedate = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        bl_patid_ed = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        registrationdate = new javax.swing.JTextField();
        bl_id_tv = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rr_patrecp_tv = new javax.swing.JTextField();
        receptionistname = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        bl_patfname_ed = new javax.swing.JTextField();
        bl_status_ed = new javax.swing.JTextField();
        bl_paidstatus_ed = new javax.swing.JTextField();
        _searching_error = new javax.swing.JLabel();
        bl_patlname_ed = new javax.swing.JTextField();
        _discharge_error = new javax.swing.JLabel();
        searching = new javax.swing.JButton();
        bl_searchingid_ed = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        _admitid_error = new javax.swing.JLabel();
        bl_chkindate_ed = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rp_registration_btn = new javax.swing.JButton();
        rp_admit_btn = new javax.swing.JButton();
        rp_bill_for_admit = new javax.swing.JButton();
        rp_opt_details = new javax.swing.JButton();
        rp_admit_details = new javax.swing.JButton();
        rp_chk_room = new javax.swing.JButton();
        rp_opt_btn = new javax.swing.JButton();
        rp_appointment_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(947, 708));
        setResizable(false);
        setSize(new java.awt.Dimension(947, 708));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/p2.png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 10, 130, 130);

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logout.setText("Logout");
        logout.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel4.add(logout);
        logout.setBounds(760, 70, 150, 30);

        jLabel6.setBackground(new java.awt.Color(0, 102, 153));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                      Receptionist Portal");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel4.add(jLabel6);
        jLabel6.setBounds(230, 50, 710, 70);

        timegetting.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        timegetting.setText("Time");
        jPanel4.add(timegetting);
        timegetting.setBounds(470, 10, 120, 30);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Admit ID");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 170, 60, 30);

        bl_discharge_ed.setEditable(false);
        bl_discharge_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_discharge_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_discharge_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_discharge_ed);
        bl_discharge_ed.setBounds(140, 270, 170, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Amount");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 370, 50, 30);

        resetall.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        resetall.setText("Reset");
        resetall.setBorder(new javax.swing.border.MatteBorder(null));
        resetall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetallActionPerformed(evt);
            }
        });
        jPanel1.add(resetall);
        resetall.setBounds(240, 130, 70, 30);

        checkedoutbtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        checkedoutbtn.setText("Check Out");
        checkedoutbtn.setBorder(new javax.swing.border.MatteBorder(null));
        checkedoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkedoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(checkedoutbtn);
        checkedoutbtn.setBounds(480, 420, 130, 40);

        bl_adid_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_adid_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_adid_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        bl_adid_ed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bl_adid_edKeyTyped(evt);
            }
        });
        jPanel1.add(bl_adid_ed);
        bl_adid_ed.setBounds(140, 170, 70, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Patient ID");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 220, 70, 30);

        bl_days_ed.setEditable(false);
        bl_days_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_days_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_days_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_days_ed);
        bl_days_ed.setBounds(140, 320, 70, 30);

        gettingadmitid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gettingadmitid.setText("Get");
        gettingadmitid.setBorder(new javax.swing.border.MatteBorder(null));
        gettingadmitid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gettingadmitidActionPerformed(evt);
            }
        });
        jPanel1.add(gettingadmitid);
        gettingadmitid.setBounds(240, 170, 70, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Status");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(270, 320, 40, 30);

        bl_amount_ed.setEditable(false);
        bl_amount_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_amount_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_amount_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_amount_ed);
        bl_amount_ed.setBounds(140, 370, 170, 30);

        gettingdischargedate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gettingdischargedate.setText("Get");
        gettingdischargedate.setBorder(new javax.swing.border.MatteBorder(null));
        gettingdischargedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gettingdischargedateActionPerformed(evt);
            }
        });
        jPanel1.add(gettingdischargedate);
        gettingdischargedate.setBounds(340, 270, 60, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Days");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(70, 320, 40, 30);

        bl_patid_ed.setEditable(false);
        bl_patid_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_patid_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_patid_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_patid_ed);
        bl_patid_ed.setBounds(140, 220, 70, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Discharge Date");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 270, 100, 30);

        registrationdate.setEditable(false);
        registrationdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registrationdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registrationdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        registrationdate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(registrationdate);
        registrationdate.setBounds(200, 10, 140, 30);

        bl_id_tv.setEditable(false);
        bl_id_tv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_id_tv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_id_tv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_id_tv);
        bl_id_tv.setBounds(140, 130, 70, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Bill Search");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(50, 90, 80, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("R ID : ");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(470, 20, 40, 30);

        rr_patrecp_tv.setEditable(false);
        rr_patrecp_tv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rr_patrecp_tv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rr_patrecp_tv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(rr_patrecp_tv);
        rr_patrecp_tv.setBounds(520, 20, 60, 30);

        receptionistname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        receptionistname.setText("Null");
        jPanel1.add(receptionistname);
        receptionistname.setBounds(520, 60, 120, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("R Name : ");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(450, 60, 60, 30);

        bl_patfname_ed.setEditable(false);
        bl_patfname_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_patfname_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_patfname_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_patfname_ed);
        bl_patfname_ed.setBounds(240, 220, 160, 30);

        bl_status_ed.setEditable(false);
        bl_status_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_status_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_status_ed.setText("OUT");
        bl_status_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_status_ed);
        bl_status_ed.setBounds(340, 320, 60, 30);

        bl_paidstatus_ed.setEditable(false);
        bl_paidstatus_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_paidstatus_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_paidstatus_ed.setText("UNPAID");
        bl_paidstatus_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_paidstatus_ed);
        bl_paidstatus_ed.setBounds(480, 340, 130, 60);

        _searching_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _searching_error.setForeground(new java.awt.Color(255, 0, 0));
        _searching_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _searching_error.setText("*");
        jPanel1.add(_searching_error);
        _searching_error.setBounds(210, 100, 20, 10);

        bl_patlname_ed.setEditable(false);
        bl_patlname_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_patlname_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_patlname_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_patlname_ed);
        bl_patlname_ed.setBounds(430, 220, 160, 30);

        _discharge_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _discharge_error.setForeground(new java.awt.Color(255, 0, 0));
        _discharge_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _discharge_error.setText("*");
        jPanel1.add(_discharge_error);
        _discharge_error.setBounds(310, 280, 20, 10);

        searching.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searching.setText("Search");
        searching.setBorder(new javax.swing.border.MatteBorder(null));
        searching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchingActionPerformed(evt);
            }
        });
        jPanel1.add(searching);
        searching.setBounds(240, 90, 70, 30);

        bl_searchingid_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_searchingid_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_searchingid_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_searchingid_ed);
        bl_searchingid_ed.setBounds(140, 90, 70, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Bill ID");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(70, 130, 50, 30);

        _admitid_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _admitid_error.setForeground(new java.awt.Color(255, 0, 0));
        _admitid_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _admitid_error.setText("*");
        jPanel1.add(_admitid_error);
        _admitid_error.setBounds(210, 180, 20, 10);

        bl_chkindate_ed.setEditable(false);
        bl_chkindate_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bl_chkindate_ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bl_chkindate_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(bl_chkindate_ed);
        bl_chkindate_ed.setBounds(430, 270, 160, 30);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(250, 170, 670, 490);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Bill For Admit");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(440, 130, 160, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        rp_registration_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_registration_btn.setText("Register Patient");
        rp_registration_btn.setBorder(new javax.swing.border.MatteBorder(null));
        rp_registration_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_registration_btnActionPerformed(evt);
            }
        });
        jPanel2.add(rp_registration_btn);
        rp_registration_btn.setBounds(10, 20, 190, 40);

        rp_admit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_admit_btn.setText("Admit Patient");
        rp_admit_btn.setBorder(new javax.swing.border.MatteBorder(null));
        rp_admit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_admit_btnActionPerformed(evt);
            }
        });
        jPanel2.add(rp_admit_btn);
        rp_admit_btn.setBounds(10, 200, 190, 40);

        rp_bill_for_admit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_bill_for_admit.setText("Bill for Admit");
        rp_bill_for_admit.setBorder(new javax.swing.border.MatteBorder(null));
        rp_bill_for_admit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_bill_for_admitActionPerformed(evt);
            }
        });
        jPanel2.add(rp_bill_for_admit);
        rp_bill_for_admit.setBounds(10, 260, 190, 40);

        rp_opt_details.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_opt_details.setText("OPT Patient Detail");
        rp_opt_details.setBorder(new javax.swing.border.MatteBorder(null));
        rp_opt_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_opt_detailsActionPerformed(evt);
            }
        });
        jPanel2.add(rp_opt_details);
        rp_opt_details.setBounds(10, 440, 190, 40);

        rp_admit_details.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_admit_details.setText("Admited Patient Detail");
        rp_admit_details.setBorder(new javax.swing.border.MatteBorder(null));
        rp_admit_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_admit_detailsActionPerformed(evt);
            }
        });
        jPanel2.add(rp_admit_details);
        rp_admit_details.setBounds(10, 380, 190, 40);

        rp_chk_room.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_chk_room.setText("Check Room");
        rp_chk_room.setBorder(new javax.swing.border.MatteBorder(null));
        rp_chk_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_chk_roomActionPerformed(evt);
            }
        });
        jPanel2.add(rp_chk_room);
        rp_chk_room.setBounds(10, 320, 190, 40);

        rp_opt_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_opt_btn.setText("Add OPT");
        rp_opt_btn.setBorder(new javax.swing.border.MatteBorder(null));
        rp_opt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_opt_btnActionPerformed(evt);
            }
        });
        jPanel2.add(rp_opt_btn);
        rp_opt_btn.setBounds(10, 80, 190, 40);

        rp_appointment_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_appointment_btn.setText("Appoinment");
        rp_appointment_btn.setBorder(new javax.swing.border.MatteBorder(null));
        rp_appointment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_appointment_btnActionPerformed(evt);
            }
        });
        jPanel2.add(rp_appointment_btn);
        rp_appointment_btn.setBounds(10, 140, 190, 40);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(20, 170, 210, 490);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 940, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    void showtime(){
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("hh:mm:ss a");
            timegetting.setText(t.format(d));
        }).start();   
    }
    
    void showdate(){
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("yyyy-MM-dd");
            registrationdate.setText(t.format(d));
            todaydate=registrationdate.getText();
        }).start(); 
    }
    
    
    
    private void resetallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetallActionPerformed
        
        _admitid_error.setVisible(false);
        _searching_error.setVisible(false);
        _discharge_error.setVisible(false);
        
        checkedoutbtn.setVisible(true);
        gettingadmitid.setVisible(true);
        gettingdischargedate.setVisible(true);
        bl_adid_ed.setEditable(true);
        
        bl_id_tv.setText(conn.getID("select billid from patientbill ORDER BY billid DESC Fetch first 1 rows only"));
        bl_searchingid_ed.setText("");
        bl_adid_ed.setText("");
        bl_patid_ed.setText("");
        bl_patfname_ed.setText("");
        bl_patlname_ed.setText("");
        bl_discharge_ed.setText("");
        bl_days_ed.setText("");
        bl_amount_ed.setText("");
        bl_chkindate_ed.setText("");
        
        
        
    }//GEN-LAST:event_resetallActionPerformed

    private void checkedoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkedoutbtnActionPerformed
        boolean emptyfld = false;
        if(bl_discharge_ed.getText().equals("")){_discharge_error.setVisible(true); emptyfld=false;}
        if(bl_adid_ed.getText().equals("")){_admitid_error.setVisible(true);emptyfld=false;}
        
        if(!bl_discharge_ed.getText().isEmpty() 
           && !bl_adid_ed.getText().isEmpty() ){emptyfld=true;}
        
        if(emptyfld == false){JOptionPane.showMessageDialog(null, "Please Fill the Fileds");}
        if(emptyfld == true){
            _discharge_error.setVisible(false);
            _admitid_error.setVisible(false);
            
            try{
                boolean another1 = false;
                boolean another2 = false; 
                conn.OpenConnection();
                String query = "insert into patientbill (adtdid,gendate,totalamount,billstatus,rid) values ("
                +bl_adid_ed.getText()+" , to_date('"+bl_discharge_ed.getText()+"','yyyy-MM-dd') , "+bl_amount_ed.getText()
                +" , 'PAID' , "+rr_patrecp_tv.getText()+")";
                int flag = conn.InsertUpdateDelete(query);
                if(flag == 1 ){another1 = true;}
                
                if(another1 == true){
                   String query2 = "update admitpatient set adtstatus='OUT' , chkout=to_date('"+bl_discharge_ed.getText()+"','yyyy-MM-dd') "
                           + " where adtdid="+bl_adid_ed.getText();
                   int flag2 = conn.InsertUpdateDelete(query2);
                   
                   if(flag2 == 1 ){another2=true;}
               
                }else{System.out.println("another 1 problem ");}
               
                if(another2 == true){
                   String query3 = "update room set rstatus='OUT' where rrid="+roomno;
                   int flag3 = conn.InsertUpdateDelete(query3);
                   
                   if(flag3 == 1 ){
                       JOptionPane.showMessageDialog(null, "Successfully CheckedOut..!");
                    bl_id_tv.setText(conn.getID("select billid from patientbill ORDER BY billid DESC Fetch first 1 rows only"));
                    
                    bl_searchingid_ed.setText("");
                    bl_adid_ed.setText("");
                    bl_patid_ed.setText("");
                    bl_patfname_ed.setText("");
                    bl_patlname_ed.setText("");
                    bl_discharge_ed.setText("");
                    bl_days_ed.setText("");
                    bl_amount_ed.setText("");
                    bl_chkindate_ed.setText("");
                   }
               }else{System.out.println("another 2 problem ");}
            
            }catch(HeadlessException e ){System.out.println(e);}
        }
        
    }//GEN-LAST:event_checkedoutbtnActionPerformed

    private void gettingadmitidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gettingadmitidActionPerformed
        if(bl_adid_ed.getText().equals("")){_admitid_error.setVisible(true);}
        if(!bl_adid_ed.getText().isEmpty()){
            _admitid_error.setVisible(false);
            boolean found = false;
           try{
               conn.OpenConnection();
               String query = "select  ad.adtdid,opt.rpid,fname,lname , chkin , ramount , r.rrid , chkout from admitpatient ad "
               + ", patientopt opt , regpatient rgp , room r , roomcategory rc where ad.optid=opt.optid and "
               + "  opt.rpid=rgp.rpid and r.rcid=rc.rcid and ad.rrid=r.rrid and ad.adtdid="+bl_adid_ed.getText()+ " and chkout is null";
               conn.GetData(query);
               while(conn.rst.next()){
                   found = true;
                   bl_patid_ed.setText(String.valueOf(conn.rst.getInt("rpid")));
                   bl_patfname_ed.setText(conn.rst.getString("fname"));
                   bl_patlname_ed.setText(conn.rst.getString("lname"));
                   String ddate=conn.rst.getString("chkin");
                   ramount=conn.rst.getInt("ramount");
                   chkoutDate=conn.rst.getString("chkout");
                   roomno = conn.rst.getInt("rrid");
                   chkinDate=ddate.substring(0,10);
                   bl_chkindate_ed.setText(chkinDate);
                   System.out.println(chkinDate + " : " + chkoutDate + " : "+roomno);
                   break;
               }
               
            if(found == false){
                JOptionPane.showMessageDialog(null, "Sorry ..! Not Found such Admit Paitent");
                bl_adid_ed.setText("");
                bl_patid_ed.setText("");
                bl_patid_ed.setText("");
                bl_patlname_ed.setText("");
            }   
           }catch(SQLException e ){System.out.println(e);}
        }
    }//GEN-LAST:event_gettingadmitidActionPerformed

    private void gettingdischargedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gettingdischargedateActionPerformed
                
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
        dischargedatee = sdf.format(date);
        bl_discharge_ed.setText(dischargedatee);
        
//        String dd1 = dischargedate.getText();
        String dd1 = todaydate;
        String dd2 = "2019-05-01";
//        String dd2 = chkinDate;
        long diff =-1;
        try{
            
            Date d1 = sdf.parse(dd1);
            Date d2 = sdf.parse(dd2);
            diff = d1.getDate()-d2.getDate();
            String totaldays = String.valueOf(diff);
            bl_days_ed.setText(totaldays);
            String amount=null;
            long tday = Long.parseLong(bl_days_ed.getText());
                // per day 1000 rupees; 
                if(tday==0){
                    amount = String.valueOf(tday+(ramount/2));
                }
                else{
                    amount = String.valueOf(tday*ramount);
                }
                bl_amount_ed.setText(amount);
                System.out.println(tday);
        }catch(ParseException e){System.out.println(e);}
        
        
        
        System.out.println(diff);
        
//        try{
//            if(bl_days_ed.getText() == null || bl_days_ed.getText().equals("")){
//                JOptionPane.showMessageDialog(null, "First get Discharge Date\n");
//                
//            }
//            else{
//                long tday = Long.parseLong(bl_days_ed.getText());
//                // per day 1000 rupees; 
//                String amount = String.valueOf(tday*1000);
//                bl_amount_ed.setText(amount);
//                System.out.println(tday);
//            }
//        }catch(NumberFormatException e ){System.out.println(e);}
        
    }//GEN-LAST:event_gettingdischargedateActionPerformed

    private void bl_adid_edKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bl_adid_edKeyTyped
        
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)  || (c==KeyEvent.VK_DELETE) )){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_bl_adid_edKeyTyped

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        LoginForm.loginsection lfl = new loginsection();
        lfl.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void rp_registration_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_registration_btnActionPerformed
        receptionist_mainmenu rmm = new receptionist_mainmenu(id,username);
        rmm.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_registration_btnActionPerformed

    private void rp_admit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_admit_btnActionPerformed
        receptionist_admitpatient radp = new receptionist_admitpatient(id,username);
        radp.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_admit_btnActionPerformed

    private void rp_bill_for_admitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_bill_for_admitActionPerformed
        receptionist_billforadmit rba = new receptionist_billforadmit(id,username);
        rba.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_bill_for_admitActionPerformed

    private void rp_opt_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_opt_detailsActionPerformed
        receptionist_optdetail roptd = new receptionist_optdetail(id,username);
        roptd.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_opt_detailsActionPerformed

    private void rp_admit_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_admit_detailsActionPerformed
        receptionist_admitpatientdetail adpd = new receptionist_admitpatientdetail(id,username);
        adpd.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_admit_detailsActionPerformed

    private void rp_chk_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_chk_roomActionPerformed
        receptionist_checkroom rchr  = new receptionist_checkroom(id,username);
        rchr.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_chk_roomActionPerformed

    private void rp_opt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_opt_btnActionPerformed
        receptionist_opt ropt = new receptionist_opt(id,username);
        ropt.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_opt_btnActionPerformed

    private void rp_appointment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_appointment_btnActionPerformed
        receptionist_appoinment rap = new receptionist_appoinment(id,username);
        rap.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_appointment_btnActionPerformed

    private void searchingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchingActionPerformed
        
        _searching_error.setVisible(false);
        _discharge_error.setVisible(false);
        
        bl_adid_ed.setText("");
        bl_patid_ed.setText("");
        bl_patfname_ed.setText("");
        bl_patlname_ed.setText("");
        bl_amount_ed.setText("");
        bl_discharge_ed.setText("");
        bl_days_ed.setText("");
        bl_amount_ed.setText("");
        bl_chkindate_ed.setText("");
        
        
        if(bl_searchingid_ed.getText().equals("")){_searching_error.setVisible(true);}
        if(!bl_searchingid_ed.getText().isEmpty()){
            
            _searching_error.setVisible(false);
            checkedoutbtn.setVisible(false);
            gettingadmitid.setVisible(false);
            gettingdischargedate.setVisible(false);
            bl_adid_ed.setEditable(false);
             boolean found = false;
           try{
               conn.OpenConnection();
               String query = "select billid, ad.adtdid , opt.rpid , fname , lname, chkin , gendate , totalamount , billstatus ,ad.adtstatus from  patientbill pb,admitpatient ad , patientopt opt , regpatient rgp  where ad.optid=opt.optid and opt.rpid=rgp.rpid  and pb.adtdid=ad.adtdid and billid="+bl_searchingid_ed.getText();
               conn.GetData(query);
               while(conn.rst.next()){
                   found = true;
                    ////
                    bl_id_tv.setText(String.valueOf(conn.rst.getInt("billid")));
                    bl_adid_ed.setText(String.valueOf(conn.rst.getInt("adtdid")));  
                    bl_patid_ed.setText(String.valueOf(conn.rst.getInt("rpid")));
                    bl_patfname_ed.setText(conn.rst.getString("fname"));
                    bl_patlname_ed.setText(conn.rst.getString("lname"));
                    bl_discharge_ed.setText(conn.rst.getString("gendate"));
                    bl_chkindate_ed.setText(conn.rst.getString("chkin"));
                    bl_amount_ed.setText(String.valueOf(conn.rst.getInt("totalamount")));
//                    bl_days_ed.setText(conn.rst.getString(""));

                    bl_status_ed.setText(conn.rst.getString("adtstatus"));
                    bl_paidstatus_ed.setText(conn.rst.getString("billstatus"));
                   ////
                   break;
               }
               
            if(found == false){
                JOptionPane.showMessageDialog(null, "Sorry ..! Not Found such Bill Paitent");
                
                bl_id_tv.setText(conn.getID("select billid from patientbill ORDER BY billid DESC Fetch first 1 rows only"));
                
                bl_adid_ed.setText("");
                bl_patid_ed.setText("");
                bl_patfname_ed.setText("");
                bl_patlname_ed.setText("");
                bl_discharge_ed.setText("");
                bl_chkindate_ed.setText("");
                bl_amount_ed.setText("");
                bl_days_ed.setText("");
                
                bl_status_ed.setText("OUT");
                bl_paidstatus_ed.setText("UNPAID");
                
                checkedoutbtn.setVisible(true);
                gettingadmitid.setVisible(true);
                gettingdischargedate.setVisible(true);
                bl_adid_ed.setEditable(true);
                
            } 
           conn.CloseConnection(); 
           }catch(SQLException e ){System.out.println(e);}
            
        }
        
    }//GEN-LAST:event_searchingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receptionist_billforadmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new receptionist_billforadmit().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _admitid_error;
    private javax.swing.JLabel _discharge_error;
    private javax.swing.JLabel _searching_error;
    private javax.swing.JTextField bl_adid_ed;
    private javax.swing.JTextField bl_amount_ed;
    private javax.swing.JTextField bl_chkindate_ed;
    private javax.swing.JTextField bl_days_ed;
    private javax.swing.JTextField bl_discharge_ed;
    private javax.swing.JTextField bl_id_tv;
    private javax.swing.JTextField bl_paidstatus_ed;
    private javax.swing.JTextField bl_patfname_ed;
    private javax.swing.JTextField bl_patid_ed;
    private javax.swing.JTextField bl_patlname_ed;
    private javax.swing.JTextField bl_searchingid_ed;
    private javax.swing.JTextField bl_status_ed;
    private javax.swing.JButton checkedoutbtn;
    private javax.swing.JButton gettingadmitid;
    private javax.swing.JButton gettingdischargedate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logout;
    private javax.swing.JLabel receptionistname;
    private javax.swing.JTextField registrationdate;
    private javax.swing.JButton resetall;
    private javax.swing.JButton rp_admit_btn;
    private javax.swing.JButton rp_admit_details;
    private javax.swing.JButton rp_appointment_btn;
    private javax.swing.JButton rp_bill_for_admit;
    private javax.swing.JButton rp_chk_room;
    private javax.swing.JButton rp_opt_btn;
    private javax.swing.JButton rp_opt_details;
    private javax.swing.JButton rp_registration_btn;
    private javax.swing.JTextField rr_patrecp_tv;
    private javax.swing.JButton searching;
    private javax.swing.JLabel timegetting;
    // End of variables declaration//GEN-END:variables
}
