/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReceptionistPortal;

import LoginForm.loginsection;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author AbdulRehman
 */
public class receptionist_mainmenu extends javax.swing.JFrame {

    String gender =null;
    
    
    /**
     * Creates new form receptionist_mainmenu
     */
    public receptionist_mainmenu() {
        initComponents();
        showdate();
        showtime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    void showtime(){
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("hh:mm:ss a");
            timegetting.setText(t.format(d));
        }).start();   
    }
    
    void showdate(){
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("yyyy-MM-dd");
            registrationdate.setText(t.format(d));
        }).start();
        
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        registrationdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rr_patlname_et = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rr_patphno_et = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rr_patage_et = new javax.swing.JTextField();
        rr_patdob_et = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        rr_patcity_combo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        rr_pataddress_et = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rr_patfname_et = new javax.swing.JTextField();
        gettingdate = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        rr_patregbill_ed = new javax.swing.JTextField();
        rr_patrecp_tv = new javax.swing.JTextField();
        receptionistname = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        adddata = new javax.swing.JButton();
        _dob_error = new javax.swing.JLabel();
        _fname_error = new javax.swing.JLabel();
        _lname_error = new javax.swing.JLabel();
        _age_error = new javax.swing.JLabel();
        _phoneno_error = new javax.swing.JLabel();
        _address_error = new javax.swing.JLabel();
        _fname_error7 = new javax.swing.JLabel();
        _city_error = new javax.swing.JLabel();
        a_recgender_combo = new javax.swing.JComboBox<>();
        rr_patid_tv = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        timegetting = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rp_registration_btn = new javax.swing.JButton();
        rp_admit_btn = new javax.swing.JButton();
        rp_bill_for_admit = new javax.swing.JButton();
        rp_opt_details = new javax.swing.JButton();
        rp_admit_details = new javax.swing.JButton();
        rp_chk_room = new javax.swing.JButton();
        rp_opt_btn = new javax.swing.JButton();
        rp_appointment_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(947, 708));
        setResizable(false);
        setSize(new java.awt.Dimension(947, 708));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/p2.png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 10, 130, 130);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        registrationdate.setEditable(false);
        registrationdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registrationdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registrationdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        registrationdate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(registrationdate);
        registrationdate.setBounds(240, 10, 130, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Last Name");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 160, 70, 30);

        rr_patlname_et.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rr_patlname_et.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(rr_patlname_et);
        rr_patlname_et.setBounds(120, 160, 140, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Phone No.");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 330, 60, 30);

        rr_patphno_et.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rr_patphno_et.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(rr_patphno_et);
        rr_patphno_et.setBounds(120, 330, 140, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("First Name");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 110, 70, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Date of Birth");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 210, 80, 30);

        rr_patage_et.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rr_patage_et.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rr_patage_et.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        rr_patage_et.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rr_patage_etKeyTyped(evt);
            }
        });
        jPanel3.add(rr_patage_et);
        rr_patage_et.setBounds(120, 290, 60, 30);

        rr_patdob_et.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(rr_patdob_et);
        rr_patdob_et.setBounds(120, 210, 140, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Gender");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(50, 250, 50, 30);

        rr_patcity_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(rr_patcity_combo);
        rr_patcity_combo.setBounds(460, 210, 120, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Address");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(40, 370, 50, 30);

        rr_pataddress_et.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rr_pataddress_et.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(rr_pataddress_et);
        rr_pataddress_et.setBounds(120, 370, 500, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Age");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(60, 290, 30, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Patient ID : ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 70, 70, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Registration Fee Rs: ");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(330, 160, 120, 30);

        rr_patfname_et.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rr_patfname_et.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        rr_patfname_et.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(rr_patfname_et);
        rr_patfname_et.setBounds(120, 110, 140, 30);

        gettingdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gettingdate.setText("Get");
        gettingdate.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(gettingdate);
        gettingdate.setBounds(210, 290, 50, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("City");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(420, 210, 30, 30);

        rr_patregbill_ed.setEditable(false);
        rr_patregbill_ed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rr_patregbill_ed.setText("1000");
        rr_patregbill_ed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        rr_patregbill_ed.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(rr_patregbill_ed);
        rr_patregbill_ed.setBounds(460, 160, 60, 30);

        rr_patrecp_tv.setEditable(false);
        rr_patrecp_tv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rr_patrecp_tv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rr_patrecp_tv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(rr_patrecp_tv);
        rr_patrecp_tv.setBounds(520, 20, 60, 30);

        receptionistname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        receptionistname.setText("Null");
        jPanel3.add(receptionistname);
        receptionistname.setBounds(520, 60, 120, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("R ID : ");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(470, 20, 40, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("R Name : ");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(450, 60, 60, 30);

        adddata.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adddata.setText("ADD");
        adddata.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(adddata);
        adddata.setBounds(270, 430, 150, 40);

        _dob_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _dob_error.setForeground(new java.awt.Color(255, 0, 0));
        _dob_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _dob_error.setText("*");
        jPanel3.add(_dob_error);
        _dob_error.setBounds(260, 220, 20, 10);

        _fname_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _fname_error.setForeground(new java.awt.Color(255, 0, 0));
        _fname_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _fname_error.setText("*");
        jPanel3.add(_fname_error);
        _fname_error.setBounds(260, 120, 20, 10);

        _lname_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _lname_error.setForeground(new java.awt.Color(255, 0, 0));
        _lname_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lname_error.setText("*");
        jPanel3.add(_lname_error);
        _lname_error.setBounds(260, 170, 20, 10);

        _age_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _age_error.setForeground(new java.awt.Color(255, 0, 0));
        _age_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _age_error.setText("*");
        jPanel3.add(_age_error);
        _age_error.setBounds(180, 300, 20, 10);

        _phoneno_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _phoneno_error.setForeground(new java.awt.Color(255, 0, 0));
        _phoneno_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _phoneno_error.setText("*");
        jPanel3.add(_phoneno_error);
        _phoneno_error.setBounds(260, 340, 20, 10);

        _address_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _address_error.setForeground(new java.awt.Color(255, 0, 0));
        _address_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _address_error.setText("*");
        jPanel3.add(_address_error);
        _address_error.setBounds(620, 380, 20, 10);

        _fname_error7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _fname_error7.setForeground(new java.awt.Color(255, 0, 0));
        _fname_error7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _fname_error7.setText("*");
        jPanel3.add(_fname_error7);
        _fname_error7.setBounds(260, 260, 20, 10);

        _city_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _city_error.setForeground(new java.awt.Color(255, 0, 0));
        _city_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _city_error.setText("*");
        jPanel3.add(_city_error);
        _city_error.setBounds(580, 220, 20, 10);

        a_recgender_combo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        a_recgender_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender" }));
        jPanel3.add(a_recgender_combo);
        a_recgender_combo.setBounds(120, 250, 140, 30);

        rr_patid_tv.setEditable(false);
        rr_patid_tv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rr_patid_tv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rr_patid_tv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.add(rr_patid_tv);
        rr_patid_tv.setBounds(120, 70, 59, 30);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(250, 170, 670, 490);

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logout.setText("Logout");
        logout.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel4.add(logout);
        logout.setBounds(760, 70, 150, 30);

        jLabel6.setBackground(new java.awt.Color(0, 102, 153));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                      Receptionist Portal");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel4.add(jLabel6);
        jLabel6.setBounds(230, 50, 710, 70);

        timegetting.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        timegetting.setText("Time");
        jPanel4.add(timegetting);
        timegetting.setBounds(500, 10, 120, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Register Patient");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(470, 130, 190, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        rp_registration_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_registration_btn.setText("Register Patient");
        rp_registration_btn.setBorder(new javax.swing.border.MatteBorder(null));
        rp_registration_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_registration_btnActionPerformed(evt);
            }
        });
        jPanel2.add(rp_registration_btn);
        rp_registration_btn.setBounds(10, 20, 190, 40);

        rp_admit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_admit_btn.setText("Admit Patient");
        rp_admit_btn.setBorder(new javax.swing.border.MatteBorder(null));
        rp_admit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_admit_btnActionPerformed(evt);
            }
        });
        jPanel2.add(rp_admit_btn);
        rp_admit_btn.setBounds(10, 200, 190, 40);

        rp_bill_for_admit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_bill_for_admit.setText("Bill for Admit");
        rp_bill_for_admit.setBorder(new javax.swing.border.MatteBorder(null));
        rp_bill_for_admit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_bill_for_admitActionPerformed(evt);
            }
        });
        jPanel2.add(rp_bill_for_admit);
        rp_bill_for_admit.setBounds(10, 260, 190, 40);

        rp_opt_details.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_opt_details.setText("OPT Patient Detail");
        rp_opt_details.setBorder(new javax.swing.border.MatteBorder(null));
        rp_opt_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_opt_detailsActionPerformed(evt);
            }
        });
        jPanel2.add(rp_opt_details);
        rp_opt_details.setBounds(10, 440, 190, 40);

        rp_admit_details.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_admit_details.setText("Admited Patient Detail");
        rp_admit_details.setBorder(new javax.swing.border.MatteBorder(null));
        rp_admit_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_admit_detailsActionPerformed(evt);
            }
        });
        jPanel2.add(rp_admit_details);
        rp_admit_details.setBounds(10, 380, 190, 40);

        rp_chk_room.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_chk_room.setText("Check Room");
        rp_chk_room.setBorder(new javax.swing.border.MatteBorder(null));
        rp_chk_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_chk_roomActionPerformed(evt);
            }
        });
        jPanel2.add(rp_chk_room);
        rp_chk_room.setBounds(10, 320, 190, 40);

        rp_opt_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_opt_btn.setText("Add OPT");
        rp_opt_btn.setBorder(new javax.swing.border.MatteBorder(null));
        rp_opt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_opt_btnActionPerformed(evt);
            }
        });
        jPanel2.add(rp_opt_btn);
        rp_opt_btn.setBounds(10, 80, 190, 40);

        rp_appointment_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rp_appointment_btn.setText("Appoinment");
        rp_appointment_btn.setBorder(new javax.swing.border.MatteBorder(null));
        rp_appointment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_appointment_btnActionPerformed(evt);
            }
        });
        jPanel2.add(rp_appointment_btn);
        rp_appointment_btn.setBounds(10, 140, 190, 40);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(20, 170, 210, 490);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 940, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rr_patage_etKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rr_patage_etKeyTyped
       
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)  || (c==KeyEvent.VK_DELETE) )){
            getToolkit().beep();
            evt.consume();
        }
        
       if(rr_patage_et.getText().length() ==2 ){
           if((Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)  || (c==KeyEvent.VK_DELETE) )){
                getToolkit().beep();
                evt.consume();
            }
       }
       
       if(rr_patage_et.getText().length() == 2){
           rr_patage_et.requestFocusInWindow();
           
       }
       
    }//GEN-LAST:event_rr_patage_etKeyTyped

    private void rp_registration_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_registration_btnActionPerformed
        receptionist_mainmenu rmm = new receptionist_mainmenu();
        rmm.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_registration_btnActionPerformed

    private void rp_admit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_admit_btnActionPerformed
        receptionist_admitpatient radp = new receptionist_admitpatient();
        radp.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_admit_btnActionPerformed

    private void rp_bill_for_admitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_bill_for_admitActionPerformed
        receptionist_billforadmit rba = new receptionist_billforadmit();
        rba.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_bill_for_admitActionPerformed

    private void rp_opt_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_opt_detailsActionPerformed
        receptionist_optdetail roptd = new receptionist_optdetail();
        roptd.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_opt_detailsActionPerformed

    private void rp_admit_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_admit_detailsActionPerformed
        receptionist_admitpatientdetail adpd = new receptionist_admitpatientdetail();
        adpd.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_admit_detailsActionPerformed

    private void rp_chk_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_chk_roomActionPerformed
        receptionist_checkroom rchr  = new receptionist_checkroom();
        rchr.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_chk_roomActionPerformed

    private void rp_opt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_opt_btnActionPerformed
        receptionist_opt ropt = new receptionist_opt();
        ropt.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_opt_btnActionPerformed

    private void rp_appointment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_appointment_btnActionPerformed
        receptionist_appoinment rap = new receptionist_appoinment();
        rap.setVisible(true);
        dispose();
    }//GEN-LAST:event_rp_appointment_btnActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        LoginForm.loginsection lfl = new loginsection();
        lfl.setVisible(true);
        dispose();        
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receptionist_mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new receptionist_mainmenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _address_error;
    private javax.swing.JLabel _age_error;
    private javax.swing.JLabel _city_error;
    private javax.swing.JLabel _dob_error;
    private javax.swing.JLabel _fname_error;
    private javax.swing.JLabel _fname_error7;
    private javax.swing.JLabel _lname_error;
    private javax.swing.JLabel _phoneno_error;
    private javax.swing.JComboBox<String> a_recgender_combo;
    private javax.swing.JButton adddata;
    private javax.swing.JButton gettingdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logout;
    private javax.swing.JLabel receptionistname;
    private javax.swing.JTextField registrationdate;
    private javax.swing.JButton rp_admit_btn;
    private javax.swing.JButton rp_admit_details;
    private javax.swing.JButton rp_appointment_btn;
    private javax.swing.JButton rp_bill_for_admit;
    private javax.swing.JButton rp_chk_room;
    private javax.swing.JButton rp_opt_btn;
    private javax.swing.JButton rp_opt_details;
    private javax.swing.JButton rp_registration_btn;
    private javax.swing.JTextField rr_pataddress_et;
    private javax.swing.JTextField rr_patage_et;
    private javax.swing.JComboBox<String> rr_patcity_combo;
    private com.toedter.calendar.JDateChooser rr_patdob_et;
    private javax.swing.JTextField rr_patfname_et;
    private javax.swing.JTextField rr_patid_tv;
    private javax.swing.JTextField rr_patlname_et;
    private javax.swing.JTextField rr_patphno_et;
    private javax.swing.JTextField rr_patrecp_tv;
    private javax.swing.JTextField rr_patregbill_ed;
    private javax.swing.JLabel timegetting;
    // End of variables declaration//GEN-END:variables
}
