/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminpPortal;

import AdminpPortal.admin_internalclasses.*;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author AbdulRehman
 */
public class admin_internal extends javax.swing.JFrame {

    /**
     * Creates new form admin_internal
     */
    public admin_internal() {
        initComponents();
        showtime();
        showdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        timegetting = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        registrationdate = new javax.swing.JTextField();
        ad_internal_roomcate = new javax.swing.JButton();
        ad_internal_qual = new javax.swing.JButton();
        ad_internal_ward = new javax.swing.JButton();
        ad_internal_room = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        a_doctor_btn = new javax.swing.JButton();
        a_nurse_btn = new javax.swing.JButton();
        a_receptionist_btn = new javax.swing.JButton();
        a_internall_btn = new javax.swing.JButton();
        a_salay_btn = new javax.swing.JButton();
        a_detail_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(947, 708));
        setResizable(false);
        setSize(new java.awt.Dimension(947, 708));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/admin (1).png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 10, 130, 130);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));
        jPanel4.add(jButton1);
        jButton1.setBounds(760, 70, 150, 30);

        jLabel6.setBackground(new java.awt.Color(0, 102, 153));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                      ADMIN Portal");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel4.add(jLabel6);
        jLabel6.setBounds(230, 50, 710, 70);

        timegetting.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        timegetting.setText("Time");
        jPanel4.add(timegetting);
        timegetting.setBounds(520, 10, 120, 30);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        registrationdate.setEditable(false);
        registrationdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registrationdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(registrationdate);
        registrationdate.setBounds(260, 20, 140, 30);

        ad_internal_roomcate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ad_internal_roomcate.setText("Room Cate");
        ad_internal_roomcate.setBorder(new javax.swing.border.MatteBorder(null));
        ad_internal_roomcate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_internal_roomcateActionPerformed(evt);
            }
        });
        jPanel1.add(ad_internal_roomcate);
        ad_internal_roomcate.setBounds(170, 240, 150, 40);

        ad_internal_qual.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ad_internal_qual.setText("Qualification");
        ad_internal_qual.setBorder(new javax.swing.border.MatteBorder(null));
        ad_internal_qual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_internal_qualActionPerformed(evt);
            }
        });
        jPanel1.add(ad_internal_qual);
        ad_internal_qual.setBounds(170, 170, 150, 40);

        ad_internal_ward.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ad_internal_ward.setText("Ward");
        ad_internal_ward.setBorder(new javax.swing.border.MatteBorder(null));
        ad_internal_ward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_internal_wardActionPerformed(evt);
            }
        });
        jPanel1.add(ad_internal_ward);
        ad_internal_ward.setBounds(360, 170, 150, 40);

        ad_internal_room.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ad_internal_room.setText("Rooms");
        ad_internal_room.setBorder(new javax.swing.border.MatteBorder(null));
        ad_internal_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_internal_roomActionPerformed(evt);
            }
        });
        jPanel1.add(ad_internal_room);
        ad_internal_room.setBounds(360, 240, 150, 40);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(230, 160, 700, 500);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Internal Adding");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(470, 120, 180, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        a_doctor_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_doctor_btn.setText("Doctor");
        a_doctor_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_doctor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_doctor_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_doctor_btn);
        a_doctor_btn.setBounds(10, 50, 190, 40);

        a_nurse_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_nurse_btn.setText("Nurse");
        a_nurse_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_nurse_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_nurse_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_nurse_btn);
        a_nurse_btn.setBounds(10, 170, 190, 40);

        a_receptionist_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_receptionist_btn.setText("Receptionist");
        a_receptionist_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_receptionist_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_receptionist_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_receptionist_btn);
        a_receptionist_btn.setBounds(10, 110, 190, 40);

        a_internall_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_internall_btn.setText("Internal");
        a_internall_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_internall_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_internall_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_internall_btn);
        a_internall_btn.setBounds(10, 350, 190, 40);

        a_salay_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_salay_btn.setText("Salary");
        a_salay_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_salay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_salay_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_salay_btn);
        a_salay_btn.setBounds(10, 230, 190, 40);

        a_detail_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_detail_btn.setText("Details");
        a_detail_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_detail_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_detail_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_detail_btn);
        a_detail_btn.setBounds(10, 290, 190, 40);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(10, 160, 210, 500);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 940, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    void showtime(){
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("hh:mm:ss a");
            timegetting.setText(t.format(d));
        }).start();   
    }
    
    void showdate(){
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("yyyy-MM-dd");
            registrationdate.setText(t.format(d));
        }).start();
        
    }
    
    private void a_doctor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_doctor_btnActionPerformed
        admin_adddoctor add = new admin_adddoctor();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_doctor_btnActionPerformed

    private void a_nurse_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_nurse_btnActionPerformed
        admin_addnurse ann = new admin_addnurse();
        ann.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_nurse_btnActionPerformed

    private void a_receptionist_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_receptionist_btnActionPerformed
        admin_addreceptionist arr = new admin_addreceptionist();
        arr.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_receptionist_btnActionPerformed

    private void a_internall_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_internall_btnActionPerformed
        admin_internal att = new admin_internal();
        att.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_internall_btnActionPerformed

    private void a_salay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_salay_btnActionPerformed
        admin_salary ass = new admin_salary();
        ass.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_salay_btnActionPerformed

    private void a_detail_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_detail_btnActionPerformed
        admin_details adt = new admin_details();
        adt.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_detail_btnActionPerformed

    private void ad_internal_qualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_internal_qualActionPerformed
        admin_internal_qualification aiq = new admin_internal_qualification();
        aiq.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_internal_qualActionPerformed

    private void ad_internal_wardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_internal_wardActionPerformed
        admin_internal_ward aiw = new admin_internal_ward();
        aiw.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_internal_wardActionPerformed

    private void ad_internal_roomcateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_internal_roomcateActionPerformed
        admin_internal_roomcate airc = new admin_internal_roomcate();
        airc.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_internal_roomcateActionPerformed

    private void ad_internal_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_internal_roomActionPerformed
        admin_internal_rooms air = new admin_internal_rooms();
        air.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_internal_roomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_internal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new admin_internal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a_detail_btn;
    private javax.swing.JButton a_doctor_btn;
    private javax.swing.JButton a_internall_btn;
    private javax.swing.JButton a_nurse_btn;
    private javax.swing.JButton a_receptionist_btn;
    private javax.swing.JButton a_salay_btn;
    private javax.swing.JButton ad_internal_qual;
    private javax.swing.JButton ad_internal_room;
    private javax.swing.JButton ad_internal_roomcate;
    private javax.swing.JButton ad_internal_ward;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField registrationdate;
    private javax.swing.JLabel timegetting;
    // End of variables declaration//GEN-END:variables
}
