/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminpPortal;

import AdminpPortal.admin_detailsclasses.*;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;


/**
 *
 * @author AbdulRehman
 */
public class admin_details extends javax.swing.JFrame {

    /**
     * Creates new form admin_patient
     */
    public admin_details() {
        initComponents();
        showdate();
        showtime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        timegetting = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        registrationdate = new javax.swing.JTextField();
        ad_details_billofadmit = new javax.swing.JButton();
        ad_details_registration = new javax.swing.JButton();
        ad_details_admitpatient = new javax.swing.JButton();
        ad_details_opt = new javax.swing.JButton();
        ad_details_rooms = new javax.swing.JButton();
        ad_details_doctor = new javax.swing.JButton();
        ad_details_nurse = new javax.swing.JButton();
        ad_details_receptionist = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        a_doctor_btn = new javax.swing.JButton();
        a_nurse_btn = new javax.swing.JButton();
        a_receptionist_btn = new javax.swing.JButton();
        a_internall_btn = new javax.swing.JButton();
        a_salay_btn = new javax.swing.JButton();
        a_detail_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(947, 708));
        setResizable(false);
        setSize(new java.awt.Dimension(947, 708));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/admin (1).png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 10, 130, 130);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));
        jPanel4.add(jButton1);
        jButton1.setBounds(760, 70, 150, 30);

        jLabel6.setBackground(new java.awt.Color(0, 102, 153));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                      ADMIN Portal");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel4.add(jLabel6);
        jLabel6.setBounds(230, 50, 710, 70);

        timegetting.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        timegetting.setText("Time");
        jPanel4.add(timegetting);
        timegetting.setBounds(510, 10, 120, 30);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        registrationdate.setEditable(false);
        registrationdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registrationdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.add(registrationdate);
        registrationdate.setBounds(260, 20, 140, 30);

        ad_details_billofadmit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ad_details_billofadmit.setText("Bill of Admit");
        ad_details_billofadmit.setBorder(new javax.swing.border.MatteBorder(null));
        ad_details_billofadmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_details_billofadmitActionPerformed(evt);
            }
        });
        jPanel1.add(ad_details_billofadmit);
        ad_details_billofadmit.setBounds(380, 190, 160, 50);

        ad_details_registration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ad_details_registration.setText("Registered Patient");
        ad_details_registration.setBorder(new javax.swing.border.MatteBorder(null));
        ad_details_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_details_registrationActionPerformed(evt);
            }
        });
        jPanel1.add(ad_details_registration);
        ad_details_registration.setBounds(160, 120, 160, 50);

        ad_details_admitpatient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ad_details_admitpatient.setText("Admited Patient");
        ad_details_admitpatient.setBorder(new javax.swing.border.MatteBorder(null));
        ad_details_admitpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_details_admitpatientActionPerformed(evt);
            }
        });
        jPanel1.add(ad_details_admitpatient);
        ad_details_admitpatient.setBounds(160, 190, 160, 50);

        ad_details_opt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ad_details_opt.setText("OPT");
        ad_details_opt.setBorder(new javax.swing.border.MatteBorder(null));
        ad_details_opt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_details_optActionPerformed(evt);
            }
        });
        jPanel1.add(ad_details_opt);
        ad_details_opt.setBounds(380, 120, 160, 50);

        ad_details_rooms.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ad_details_rooms.setText("Rooms");
        ad_details_rooms.setBorder(new javax.swing.border.MatteBorder(null));
        ad_details_rooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_details_roomsActionPerformed(evt);
            }
        });
        jPanel1.add(ad_details_rooms);
        ad_details_rooms.setBounds(380, 260, 160, 50);

        ad_details_doctor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ad_details_doctor.setText("Doctor");
        ad_details_doctor.setBorder(new javax.swing.border.MatteBorder(null));
        ad_details_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_details_doctorActionPerformed(evt);
            }
        });
        jPanel1.add(ad_details_doctor);
        ad_details_doctor.setBounds(160, 260, 160, 50);

        ad_details_nurse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ad_details_nurse.setText("Nurse");
        ad_details_nurse.setBorder(new javax.swing.border.MatteBorder(null));
        ad_details_nurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_details_nurseActionPerformed(evt);
            }
        });
        jPanel1.add(ad_details_nurse);
        ad_details_nurse.setBounds(380, 330, 160, 50);

        ad_details_receptionist.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ad_details_receptionist.setText("Receptionist");
        ad_details_receptionist.setBorder(new javax.swing.border.MatteBorder(null));
        ad_details_receptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_details_receptionistActionPerformed(evt);
            }
        });
        jPanel1.add(ad_details_receptionist);
        ad_details_receptionist.setBounds(160, 330, 160, 50);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(230, 160, 690, 500);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("All Details");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(500, 120, 140, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        a_doctor_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_doctor_btn.setText("Doctor");
        a_doctor_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_doctor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_doctor_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_doctor_btn);
        a_doctor_btn.setBounds(10, 50, 190, 40);

        a_nurse_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_nurse_btn.setText("Nurse");
        a_nurse_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_nurse_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_nurse_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_nurse_btn);
        a_nurse_btn.setBounds(10, 170, 190, 40);

        a_receptionist_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_receptionist_btn.setText("Receptionist");
        a_receptionist_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_receptionist_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_receptionist_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_receptionist_btn);
        a_receptionist_btn.setBounds(10, 110, 190, 40);

        a_internall_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_internall_btn.setText("Internal");
        a_internall_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_internall_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_internall_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_internall_btn);
        a_internall_btn.setBounds(10, 350, 190, 40);

        a_salay_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_salay_btn.setText("Salary");
        a_salay_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_salay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_salay_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_salay_btn);
        a_salay_btn.setBounds(10, 230, 190, 40);

        a_detail_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        a_detail_btn.setText("Details");
        a_detail_btn.setBorder(new javax.swing.border.MatteBorder(null));
        a_detail_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_detail_btnActionPerformed(evt);
            }
        });
        jPanel2.add(a_detail_btn);
        a_detail_btn.setBounds(10, 290, 190, 40);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(10, 160, 210, 500);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 940, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void showtime(){
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("hh:mm:ss a");
            timegetting.setText(t.format(d));
        }).start();   
    }
    
    void showdate(){
        new Timer(0, (ActionEvent ae) -> {
            Date d = new Date();
            SimpleDateFormat t = new SimpleDateFormat("yyyy-MM-dd");
            registrationdate.setText(t.format(d));
        }).start();
        
    }
    
    private void ad_details_optActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_details_optActionPerformed
        // TODO add your handling code here:
        admin_details_opt opt = new admin_details_opt();
        opt.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_details_optActionPerformed

    private void ad_details_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_details_registrationActionPerformed
        admin_details_registration ag = new admin_details_registration();
        ag.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_details_registrationActionPerformed

    private void ad_details_admitpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_details_admitpatientActionPerformed
        admin_details_admit ada = new admin_details_admit();
        ada.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_details_admitpatientActionPerformed

    private void ad_details_billofadmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_details_billofadmitActionPerformed
        admin_details_billforadmit ab = new admin_details_billforadmit();
        ab.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_details_billofadmitActionPerformed

    private void ad_details_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_details_doctorActionPerformed
        admin_details_doctor ad = new admin_details_doctor();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_details_doctorActionPerformed

    private void ad_details_nurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_details_nurseActionPerformed
        admin_details_nurse an = new admin_details_nurse();
        an.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_details_nurseActionPerformed

    private void ad_details_roomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_details_roomsActionPerformed
        admin_details_rooms adr = new admin_details_rooms();
        adr.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_details_roomsActionPerformed

    private void ad_details_receptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_details_receptionistActionPerformed
        admin_details_receptionist adrr = new admin_details_receptionist();
        adrr.setVisible(true);
        dispose();
    }//GEN-LAST:event_ad_details_receptionistActionPerformed

    private void a_doctor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_doctor_btnActionPerformed
        admin_adddoctor add = new admin_adddoctor();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_doctor_btnActionPerformed

    private void a_nurse_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_nurse_btnActionPerformed
        admin_addnurse ann = new admin_addnurse();
        ann.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_nurse_btnActionPerformed

    private void a_receptionist_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_receptionist_btnActionPerformed
        admin_addreceptionist arr = new admin_addreceptionist();
        arr.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_receptionist_btnActionPerformed

    private void a_internall_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_internall_btnActionPerformed
        admin_internal att = new admin_internal();
        att.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_internall_btnActionPerformed

    private void a_salay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_salay_btnActionPerformed
        admin_salary ass = new admin_salary();
        ass.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_salay_btnActionPerformed

    private void a_detail_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_detail_btnActionPerformed
        admin_details adt = new admin_details();
        adt.setVisible(true);
        dispose();
    }//GEN-LAST:event_a_detail_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a_detail_btn;
    private javax.swing.JButton a_doctor_btn;
    private javax.swing.JButton a_internall_btn;
    private javax.swing.JButton a_nurse_btn;
    private javax.swing.JButton a_receptionist_btn;
    private javax.swing.JButton a_salay_btn;
    private javax.swing.JButton ad_details_admitpatient;
    private javax.swing.JButton ad_details_billofadmit;
    private javax.swing.JButton ad_details_doctor;
    private javax.swing.JButton ad_details_nurse;
    private javax.swing.JButton ad_details_opt;
    private javax.swing.JButton ad_details_receptionist;
    private javax.swing.JButton ad_details_registration;
    private javax.swing.JButton ad_details_rooms;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField registrationdate;
    private javax.swing.JLabel timegetting;
    // End of variables declaration//GEN-END:variables
}
